apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elastic-smapp
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:6.6.1
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch-master.elastic-smapp:9200"
            - name: SERVER_BASEPATH
              value: "/kibana"
            - name: SERVER_REWRITEBASEPATH
              value: "false"
            - name: requestTimeout
              value: 60000
---
apiVersion: v1
kind: Service
metadata:
  namespace: elastic-smapp
  name: kibana
  labels:
    app: kibana
spec:
  clusterIP: None
  selector:
    app: kibana
  ports:
    - port: 5601
      name: http
  type: ClusterIP
