apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elastic-smapp
  name: flask-app-example
  labels:
    app: flask-app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-example
  template:
    metadata:
      name: flask-app-example
      labels:
        app: flask-app-example
    spec:
      containers:
        - name: flask-app-example
          image: crazyfrogspb/app_example
          ports:
            - containerPort: 8080
          env:
            - name: DEBUG_MODE
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  namespace: elastic-smapp
  name: flask-app-example
  labels:
    app: flask-app-example
spec:
  clusterIP: None
  selector:
    app: flask-app-example
  ports:
    - port: 8080
      name: http
  type: ClusterIP
